#!/bin/bash -eu
#
# Dump all mysql databases into separate files.
# Save to /etc/cron.daily/daily-mysqldump to run daily.
#
# Copyright 2018 Jakob Unterwurzacher
# Latest version: https://github.com/rfjakob/servertools
# SPDX-License-Identifier: MIT

DIR=/daily-mysqldump

DBS=$(mysql --defaults-file=/etc/mysql/debian.cnf -N -s -e "show databases" | \
 grep -E -v "(information_schema|performance_schema)")

for DB in $DBS ; do
	mysqldump --defaults-file=/etc/mysql/debian.cnf --events --ignore-table=mysql.event \
	 "$DB" | xz -1 > "$DIR/$DB.sql.xz.tmp"

	mv "$DIR/$DB.sql.xz.tmp" "$DIR/$DB.sql.xz"
done

# Delete dumps where the corresponding database does not longer exist
# after 7 days
find "$DIR" -maxdepth 1 -type f \( -name "*.sql.xz" -o -name "*.sql.xz.tmp" \) -mtime +7
