#!/bin/bash
#
# cd to the directory DST is in first!
#
# Usage example:
# 
# $ cd /mirrors/server1
# $ rsync-mirror-wrapper server1:/home home
#
# Author: Jakob Unterwurzacher, 2013
# License: GPLv2 or later

set -eu

# Example: server1:/home
SRC=$1

# Example: home
DST=$2

echo "$$ `date`" > $DST.rsync-mirror-started

# "$DST/." to prevent mistakes - directory must exist beforehand.
rsync-no-vanished -ax --numeric-ids --delay-updates --delete-delay --delete-excluded \
	--exclude-from=/mirrors/exclude.txt --log-file=$DST.rsync.log \
	$SRC $DST/.

echo "$$ `date`" > $DST.rsync-mirror-success

exit 0
